name: iq_weather
description: IQ Weather App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_presentation: ^1.0.0
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.0
  intl: ^0.19.0
  iq_weather_ui:
    path: packages/iq_weather_ui
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logging: ^1.3.0
  meta: ^1.15.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_presentation_test: ^1.0.2
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  coverage: ^1.11.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  patrol: ^3.12.0
  patrol_finders: 2.1.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

patrol:
  app_name: IQ Weather
  flavor: development
  android:
    package_name: com.example.verygoodcore.iq_weather
  ios:
    bundle_id: com.example.verygoodcore.iq-weather
